--- 10-1
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

--- 10-2
SELECT * FROM DEPT_TEMP;

--- 10-3
INSERT  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
        VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

--- 10-4
INSERT  INTO DEPT_TEMP
        VALUES(60, 'NETWORK', 'BUSAN');
        
SELECT * FROM DEPT_TEMP;

--- 10-5
INSERT  INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
        VALUES(70, 'WEB', NULL);

SELECT * FROM DEPT_TEMP;

--- 10-6
INSERT  INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
        VALUES(80, 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

--- 10-7
INSERT  INTO DEPT_TEMP(DEPTNO, LOC)
        VALUES(90, 'INCHEON');

SELECT * FROM DEPT_TEMP;

--- 10-8
CREATE  TABLE EMP_TEMP
        AS SELECT *
            FROM EMP
            WHERE 1<>1;

SELECT * FROM EMP_TEMP;

--- 10-9
INSERT  INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (9999, '류지현', 'ENGINEER', NULL, '2020/09/02', 3000, 1000, 10);

SELECT * FROM EMP_TEMP;

--- 10-10
INSERT  INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (1111, '유지현', 'ENGINEER', 9999, '2020-09-02', 3000, NULL, 10);

SELECT * FROM EMP_TEMP;

--- 10-12
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR,
                     HIREDATE,
                     SAL, COMM, DEPTNO)
            VALUES(2111, '익명이', 'MANAGER', 9999,
                   TO_DATE('07/01/2001', 'DD/MM/YYYY'),
                   4000, NULL, 20);

SELECT * FROM EMP_TEMP;

--- 10-13
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR,
                     HIREDATE,
                     SAL, COMM, DEPTNO)
             VALUES(3111, '익명이2', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
 
SELECT * FROM EMP_TEMP;

--- 10-14
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
            FROM EMP E, SALGRADE S
            WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
            AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

--- 10-15
CREATE  TABLE DEPT_TEMP2
        AS SELECT * FROM DEPT;
        
SELECT * FROM DEPT_TEMP2; 

--- 10-16
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

--- 10-17
ROLLBACK;

SELECT * FROM DEPT_TEMP2;

--- 10-18
UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC = 'SEOUL'
    WHERE DEPTNO = 40;
    
SELECT * FROM DEPT_TEMP2;

--- 10-19
UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO = 40)
    WHERE DEPTNO = 40;
    
SELECT * FROM DEPT_TEMP2;

--- 10-20
UPDATE DEPT_TEMP2
    SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO=40),
        LOC   = (SELECT LOC FROM DEPT WHERE DEPTNO=40)  
    WHERE DEPTNO = 40; 
    
SELECT * FROM DEPT_TEMP2;

--- 10-21
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
    WHERE DEPTNO = (SELECT DEPTNO
                    FROM DEPT_TEMP2
                    WHERE DNAME='OPERATIONS');
                    
SELECT * FROM DEPT_TEMP2;

--- 10-22
CREATE TABLE EMP_TEMP2
       AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--- 10-23
DELETE FROM EMP_TEMP2
    WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

--- 10-24
DELETE FROM EMP_TEMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                    FROM EMP_TEMP2 E, SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DEPTNO = 30);
                    
SELECT * FROM EMP_TEMP2;

--- 10-25
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;

























