--- 13-1
SELECT * FROM DICT;

--- 13-2
SELECT * FROM DICTIONARY;

--- 13-3
SELECT TABLE_NAME
    FROM USER_TABLES;
    
--- 13-4
SELECT OWNER, TABLE_NAME
    FROM ALL_TABLES;
    
--- 13-5
SELECT * FROM DB_TABLES;

--- 13-6
SELECT * FROM DBA_TABLES;

--- 13-7
SELECT *
  FROM DBA_USERS
 WHERE USERNAME = 'SCOTT';
 
--- 13-8
SELECT *
    FROM USER_INDEXES;
    
--- 13-9
SELECT *
    FROM USER_IND_COLUMNS;
    
--- 13-10
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);

--- 13-11
SELECT * FROM USER_IND_COLUMNS;

--- 13-12
DROP INDEX IDX_EMP_SAL;

--- 13-13
SELECT * FROM USER_IND_COLUMNS;

--- 13-15
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
        FROM EMP
        WHERE DEPTNO = 20);

--- 13-16
SELECT * FROM USER_VIEWS;

--- 13-17
DROP VIEW VW_EMP20;

SELECT * FROM USER_VIEWS;

--- 13-20
SELECT ROWNUM, E.*
    FROM EMP E;

--- 13-21
SELECT ROWNUM, E.*
    FROM EMP E
    ORDER BY SAL DESC;

--- 13-22 인라인 뷰(서브쿼리 사용)
SELECT ROWNUM, E.*
    FROM(SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E;

--- 13-23 인라인 뷰(WITH절 사용)
WITH E AS (SELECT * FROM EMP ORDER BY SAL)
SELECT ROWNUM, E.*
    FROM E;
    
--- 13-24 인라인 뷰로 TOP-N 추출하기(서브쿼리 사용)
SELECT ROWNUM, E.*
    FROM(SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E
    WHERE ROWNUM <= 3;
    
--- 13-23 인라인 뷰로 TOP-N 추출하기(WITH절 사용)
WITH E AS (SELECT * FROM EMP ORDER BY SAL)
SELECT ROWNUM, E.*
    FROM E
    WHERE ROWNUM <= 3;
    
--- 13-26 DEPT 테이블을 사용하여 DEPT_SEQUENCE 테이블 생성하기
CREATE TABLE DEPT_SEQUENCE
    AS SELECT * FROM DEPT
    WHERE 1 <> 1;
    
SELECT * FROM DEPT_SEQUENCE;

--- 13-27 시퀀스 생성하기
CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 0
NOCYCLE
CACHE 2;

--- 13-28 생성한 시퀀스 확인하기
SELECT *
    FROM USER_SEQUENCES;

--- 13-29 시퀀스에서 생성한 순번을 사용한 INSERT문 실행하기
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
    VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--- 13-30 가장 마지막으로 생성된 시퀀스 확인하기
SELECT SEQ_DEPT_SEQUENCE.CURRVAL FROM DUAL;

--- 13-31 NEXTVAL를 반복 사용하여 INSERT문 실행하기
INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
    VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--- 13-32 시퀀스 옵션 수정하기
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;

--- 13-33 옵션을 수정한 시퀀스 조회하기
SELECT * FROM USER_SEQUENCES;

--- 13-34 수정한 시퀀스를 사용하여 INSERT문 실행하기
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'NEW_DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--- 13-35 시퀀스 삭제 후 확인하기
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

SELECT * FROM DEPT_SEQUENCE;

--- 13-38 EMP 테이블의 동의어 생성하기
CREATE SYNONYM E
    FOR EMP;

--- 13-39 E 테이블 전체 내용 조회하기
SELECT * FROM E;

--- 13-40 동의어 삭제하기
DROP SYNONYM E;










