--- 6-1
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

--- 6-2
SELECT *
FROM EMP
WHERE UPPER(ENAME) = UPPER('scott');

--- 6-3
SELECT *
FROM EMP
WHERE UPPER(ENAME) LIKE UPPER('%scott%');

--- 6-4
SELECT ENAME, LENGTH(ENAME)
FROM EMP;

--- 6-5
SELECT ENAME, LENGTH(ENAME)
FROM EMP
WHERE LENGTH(ENAME) >= 5;

--- 6-6
SELECT LENGTH('한글'), LENGTHB('한글')
FROM DUAL;

--- 6-7
SELECT JOB, SUBSTR(JOB,1,2), SUBSTR(JOB, 5)
FROM EMP;

--- 6-8
SELECT JOB,
       SUBSTR(JOB, -LENGTH(JOB)),
       SUBSTR(JOB, -LENGTH(JOB), 2),
       SUBSTR(JOB, -3)
FROM EMP;

--- 6-9
SELECT INSTR('HELLO, ORALCE!', 'L') AS INSTR_1,
       INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR_2,
       INSTR('HELLO, ORACLE!', 'L', 2, 2) AS INSTR_3
FROM DUAL;

--- 6-10
SELECT *
FROM EMP
WHERE INSTR(ENAME, 'S') > 0;

--- 6-11
SELECT *
FROM EMP
WHERE ENAME LIKE '%S%';

--- 6-12
SELECT '010-1234-5678' AS REPLACE_BEFORE,
       REPLACE('010-1234-5678', '-', ' ') AS REPLACE_1,
       REPLACE('010-1234-5678', '-') AS REPLACE_2
FROM DUAL;

--- 6-13
SELECT 'Oracle',
       LPAD('Oracle', 10, '#') AS LPAD_1,
       RPAD('Oracle', 10, '*') AS RPAD_1,
       LPAD('Oracle', 10) AS LPAD_2,
       RPAD('Oracle', 10) AS RPAD_2
FROM DUAL;

--- 6-14
SELECT RPAD('971208-', 14, '*') AS RPAD_JMNO,
       RPAD('010-3615', 13, '*') AS RPAD_PHONE
FROM DUAL;

--- 6-15
SELECT CONCAT(EMPNO, ENAME),
       CONCAT(EMPNO, CONCAT(':', ENAME))
FROM EMP
WHERE ENAME = 'SCOTT';

--- 6-16
SELECT '_' || TRIM(' _ _Oracle_ _ ') || '_' AS TRIM,
       '_' || TRIM(LEADING FROM ' _ _Oracle_ _ ') || '_' AS TRIM_LEADING,
       '_' || TRIM(TRAILING FROM ' _ _Oracle_ _ ') || '_' AS TRIM_TRAILING,
       '_' || TRIM(BOTH FROM ' _ _Oracle_ _ ') || '_' AS TRIM_BOTH
FROM DUAL;

--- 6-17
SELECT '_' || TRIM('_' FROM '_ _Oracle_ _') || '_' AS TRIM,
       '_' || TRIM(LEADING '_' FROM '_ _Oracle_ _') || '_' AS TRIM_LEADING,
       '_' || TRIM(TRAILING '_' FROM '_ _Oracle_ _') || '_' AS TRIM_TRAILING,
       '_' || TRIM(BOTH '_' FROM '_ _Oracle_ _') || '_' AS TRIM_BOTH
FROM DUAL; 

--- 6-18
SELECT '_' || TRIM(' _Oracle_ ') || '_' AS TRIM,
       '_' || LTRIM(' _Oracle_ ') || '_' AS LTRIM,
       '_' || LTRIM('<_Oracle_>', '_<') || '_' AS LTRIM_2,
       '_' || RTRIM(' _Oracle_ ') || '_' AS RTRIM,
       '_' || RTRIM('<_Oracle_>', '>_') || '_' AS RTRIM_2
FROM DUAL;

--- 6-19
SELECT ROUND(1234.5678) AS ROUND,
       ROUND(1234.5678, 0) AS ROUND_0,
       ROUND(1234.5678, 1) AS ROUND_1,
       ROUND(1234.5678, 2) AS ROUND_2,
       ROUND(1234.5678, -1) AS ROUND_MINUS1,
       ROUND(1234.5678, -2) AS ROUND_MINUS2
FROM DUAL;

--- 6-20
SELECT TRUNC(1234.5678) AS TRUNC,
       TRUNC(1234.5678, 0) AS TRUNC_0,
       TRUNC(1234.5678, 1) AS TRUNC_1,
       TRUNC(1234.5678, 2) AS TRUNC_2,
       TRUNC(1234.5678, -1) AS TRUNC_MINUS1,
       TRUNC(1234.5678, -2) AS TRUNC_MINUS2
FROM DUAL;

--- 6-21
SELECT CEIL(3.14),
       FLOOR(3.14),
       CEIL(-3.14),
       FLOOR(-3.14)
FROM DUAL;

--- 6-22
SELECT MOD(15, 6),
       MOD(10, 2),
       MOD(11, 2)
FROM DUAL;

--- 6-23
SELECT SYSDATE AS NOW,
       SYSDATE+1 AS TOMORROW,
       SYSDATE-1 AS YESTERDAY
FROM DUAL;

--- 6-24
SELECT SYSDATE AS NOW,
       ADD_MONTHS(SYSDATE, 3) AS AFTER3MONTH
FROM DUAL;

--- 6-25
SELECT EMPNO, ENAME, HIREDATE,
       ADD_MONTHS(SYSDATE, 120)
FROM EMP;

--- 6-26
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE ADD_MONTHS(SYSDATE, 384) > SYSDATE;

--- 6-27
SELECT ENAME, HIREDATE, SYSDATE,
       MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTHS_1,
       MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS_2,
       TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS_3
FROM EMP;

--- 6-28
SELECT SYSDATE,
       NEXT_DAY(SYSDATE, '월요일'),
       LAST_DAY(SYSDATE)
FROM DUAL;

--- 6-29
SELECT  SYSDATE,
        ROUND(SYSDATE,'CC') AS FORMAT_CC,
        ROUND(SYSDATE,'YYYY') AS FORMAT_YYYY,
        ROUND(SYSDATE,'Q') AS FORMAT_Q,
        ROUND(SYSDATE,'DDD') AS FORMAT_DDD,
        ROUND(SYSDATE,'HH') AS FORMAT_HH
FROM DUAL;

--- 6-30
SELECT  SYSDATE,
        TRUNC(SYSDATE,'CC') AS FORMAT_CC,
        TRUNC(SYSDATE,'YYYY') AS FORMAT_YYYY,
        TRUNC(SYSDATE,'Q') AS FORMAT_Q,
        TRUNC(SYSDATE,'DDD') AS FORMAT_DDD,
        TRUNC(SYSDATE,'HH') AS FORMAT_HH
FROM DUAL;
