--- 10-1
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

--- 10-2
SELECT * FROM DEPT_TEMP;

--- 10-3
INSERT  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
        VALUES (50, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_TEMP;

--- 10-4
INSERT  INTO DEPT_TEMP
        VALUES(60, 'NETWORK', 'BUSAN');
        
SELECT * FROM DEPT_TEMP;

--- 10-5
INSERT  INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
        VALUES(70, 'WEB', NULL);

SELECT * FROM DEPT_TEMP;

--- 10-6
INSERT  INTO DEPT_TEMP(DEPTNO, DNAME, LOC)
        VALUES(80, 'MOBILE', '');

SELECT * FROM DEPT_TEMP;

--- 10-7
INSERT  INTO DEPT_TEMP(DEPTNO, LOC)
        VALUES(90, 'INCHEON');

SELECT * FROM DEPT_TEMP;

--- 10-8
CREATE  TABLE EMP_TEMP
        AS SELECT *
            FROM EMP
            WHERE 1<>1;

SELECT * FROM EMP_TEMP;

--- 10-9
INSERT  INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (9999, '류지현', 'ENGINEER', NULL, '2020/09/02', 3000, 1000, 10);

SELECT * FROM EMP_TEMP;

--- 10-10
INSERT  INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            VALUES (1111, '유지현', 'ENGINEER', 9999, '2020-09-02', 3000, NULL, 10);

SELECT * FROM EMP_TEMP;

--- 10-12
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR,
                     HIREDATE,
                     SAL, COMM, DEPTNO)
            VALUES(2111, '익명이', 'MANAGER', 9999,
                   TO_DATE('07/01/2001', 'DD/MM/YYYY'),
                   4000, NULL, 20);

SELECT * FROM EMP_TEMP;

--- 10-13
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR,
                     HIREDATE,
                     SAL, COMM, DEPTNO)
             VALUES(3111, '익명이2', 'MANAGER', 9999, SYSDATE, 4000, NULL, 30);
 
SELECT * FROM EMP_TEMP;

--- 10-14
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
            SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
            FROM EMP E, SALGRADE S
            WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
            AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

--- 10-15
CREATE  TABLE DEPT_TEMP2
        AS SELECT * FROM DEPT;
        
SELECT * FROM DEPT_TEMP2; 

--- 10-16
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

--- 10-17
ROLLBACK;

SELECT * FROM DEPT_TEMP2;

--- 10-18
UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE',
        LOC = 'SEOUL'
    WHERE DEPTNO = 40;
    
SELECT * FROM DEPT_TEMP2;

--- 10-19
UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                        FROM DEPT
                        WHERE DEPTNO = 40)
    WHERE DEPTNO = 40;
    
SELECT * FROM DEPT_TEMP2;

--- 10-20
UPDATE DEPT_TEMP2
    SET DNAME = (SELECT DNAME FROM DEPT WHERE DEPTNO=40),
        LOC   = (SELECT LOC FROM DEPT WHERE DEPTNO=40)  
    WHERE DEPTNO = 40; 
    
SELECT * FROM DEPT_TEMP2;

--- 10-21
UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
    WHERE DEPTNO = (SELECT DEPTNO
                    FROM DEPT_TEMP2
                    WHERE DNAME='OPERATIONS');
                    
SELECT * FROM DEPT_TEMP2;

--- 10-22
CREATE TABLE EMP_TEMP2
       AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP2;

--- 10-23
DELETE FROM EMP_TEMP2
    WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

--- 10-24
DELETE FROM EMP_TEMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                    FROM EMP_TEMP2 E, SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 3
                    AND DEPTNO = 30);
                    
SELECT * FROM EMP_TEMP2;

--- 10-25
DELETE FROM EMP_TEMP2;

SELECT * FROM EMP_TEMP2;



--- 10-26
CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;

CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;

CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;

--- 10-27
INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (50, 'ORACLE', 'BUSAN');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (60, 'SQL', 'ILSAN');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (70, 'SELECT', 'INCHEON');

INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (80, 'DML', 'BUNDANG');

SELECT * FROM CHAP10HW_DEPT;                            

--- 10-28
INSERT INTO CHAP10HW_EMP
VALUES(7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02', 'YYYY-MM-DD'), 4500, NULL, 50);
 
INSERT INTO CHAP10HW_EMP
VALUES(7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21', 'YYYY-MM-DD'), 1800, NULL, 50);
 
INSERT INTO CHAP10HW_EMP
VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11', 'YYYY-MM-DD'), 3400, NULL, 60);
 
INSERT INTO CHAP10HW_EMP
VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31', 'YYYY-MM-DD'), 2700, 300, 60);
 
INSERT INTO CHAP10HW_EMP
VALUES(7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20', 'YYYY-MM-DD'), 2600, NULL, 70);
 
INSERT INTO CHAP10HW_EMP
VALUES(7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08', 'YYYY-MM-DD'), 2600, NULL, 70);
 
INSERT INTO CHAP10HW_EMP
VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28', 'YYYY-MM-DD'), 2300, NULL, 80);
 
INSERT INTO CHAP10HW_EMP
VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09', 'YYYY-MM-DD'), 1200, NULL, 80);

SELECT * FROM CHAP10HW_EMP;

--- 10-29
UPDATE CHAP10HW_EMP
    SET DEPTNO = 70
    WHERE SAL > (SELECT AVG(SAL) FROM CHAP10HW_EMP WHERE DEPTNO = 50);

SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO;

--- 10-30
UPDATE CHAP10HW_EMP
    SET DEPTNO = 80,
        SAL = SAL*1.1
    WHERE HIREDATE > (SELECT MIN(HIREDATE) FROM CHAP10HW_EMP WHERE DEPTNO = 60);
    
SELECT * FROM CHAP10HW_EMP ORDER BY DEPTNO;

--- 10-31
DELETE FROM CHAP10HW_EMP
 WHERE EMPNO IN (SELECT E.EMPNO
                   FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 5);

SELECT * FROM CHAP10HW_EMP;
