--- 12-1
CREATE TABLE EMP_DDL(
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(10),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COM         NUMBER(7,2),
    DEPTNO      NUMBER(2)
);

DESC EMP_DDL;

--- 12-2
CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

DESC DEPT_DDL;

--- 12-3
SELECT * FROM DEPT_DDL;

--- 12-4
CREATE TABLE EMP_DDL_30
    AS SELECT * FROM EMP WHERE DEPTNO = 30;
    
SELECT * FROM EMP_DDL_30;

--- 12-5
CREATE TABLE EMPDEPT_DDL
    AS SELECT   E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
                E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
            FROM EMP E, DEPT D
            WHERE 1<>1;
            
SELECT * FROM EMPDEPT_DDL;

--- 12-6
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

--- 12-7
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--- 12-8
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

--- 12-9
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--- 12-10
ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;
   
SELECT * FROM EMP_ALTER;

--- 12-11
RENAME EMP_ALTER TO EMP_RENAME;

DESC EMP_ALTER;

SELECT * FROM EMP_RENAME;

--- 12-12
TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

--- 12-13
DROP TABLE EMP_RENAME;

DESC EMP_RENAME;

--- 12-14
CREATE TABLE EMP_HW(
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
); 

--- 12-15
ALTER TABLE EMP_HW
    ADD BIGO VARCHAR2(20);

--- 12-16
ALTER TABLE EMP_HW
    MODIFY  BIGO VARCHAR2(30);

--- 12-17
ALTER TABLE EMP_HW
    RENAME COLUMN BIGO TO REMARK;

--- 12-18
INSERT INTO EMP_HW
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL FROM EMP;

--- 12-19
DROP TABLE EMP_HW;



    
