--- 8-1
SELECT *
    FROM EMP, DEPT
    ORDER BY EMPNO;
    
--- 8-2
SELECT *
    FROM EMP, DEPT
    WHERE EMP.DEPTNO = DEPT.DEPTNO
    ORDER BY ENAME;
    
--- 8-3
SELECT *
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY ENAME;
    
--- 8-4
SELECT EMPNO, ENAME, DEPTNO, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;

---- 8-5
SELECT EMPNO, ENAME, D.DEPTNO, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
    
--- 8-6
SELECT EMPNO, ENAME, SAL, D.DEPTNO, DNAME, LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND SAL >= 3000; 

--- 8-7
SELECT E.ENAME, E.JOB, E.SAL, S.GRADE, S.LOSAL, S.HISAL
    FROM EMP E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

--- 8-8
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1, EMP E2
        WHERE E1.MGR = E2.EMPNO;

--- 8-9
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1, EMP E2
        WHERE E1.MGR = E2.EMPNO(+)
        ORDER BY E1.EMPNO;
        
--- 8-10
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1, EMP E2
        WHERE E1.MGR(+) = E2.EMPNO
        ORDER BY E1.EMPNO;
        
--- 8-11
SELECT  E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E NATURAL JOIN DEPT D
    ORDER BY DEPTNO, E.EMPNO;
    
--- 8-12
SELECT  E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE SAL >= 3000
    ORDER BY DEPTNO, E.EMPNO;
    
--- 8-13
SELECT  E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        E.DEPTNO,
        D.DNAME, D.LOC
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE SAL <= 3000
    ORDER BY E.DEPTNO, E.EMPNO;
    
    
--- 8-14
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;
   
--- 8-15
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;

--- 8-16
SELECT  E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM EMP E1 FULL OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY E1.EMPNO;

--- 8-17(1)
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND SAL > 2000;
    
--- 8-17(2)
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E JOIN DEPT D ON (D.DEPTNO = E.DEPTNO)
    WHERE SAL > 2000;
    
--- 8-18(1)
SELECT  D.DEPTNO, D.DNAME,
        N.AVG_SAL, N.MAX_SAL, N.MIN_SAL, N.CNT
     FROM DEPT D, (SELECT  DEPTNO,TRUNC(AVG(SAL), 0) AS AVG_SAL,
                        MAX(SAL) AS MAX_SAL,
                        MIN(SAL) AS MIN_SAL,
                        COUNT(SAL) AS CNT
                    FROM EMP
                    GROUP BY DEPTNO) N
    WHERE D.DEPTNO = N.DEPTNO
    ORDER BY DEPTNO;

--- 8-18(2)
SELECT  D.DEPTNO, D.DNAME,
        N.AVG_SAL, N.MAX_SAL, N.MIN_SAL, N.CNT
     FROM DEPT D JOIN (SELECT  DEPTNO,TRUNC(AVG(SAL), 0) AS AVG_SAL,
                        MAX(SAL) AS MAX_SAL,
                        MIN(SAL) AS MIN_SAL,
                        COUNT(SAL) AS CNT
                    FROM EMP
                    GROUP BY DEPTNO) N ON (D.DEPTNO = N.DEPTNO)
    ORDER BY DEPTNO;
    
--- 8-19(1)
SELECT  D.DEPTNO,
        D.DNAME, E.ENAME, E.JOB, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO(+) = D.DEPTNO
    ORDER BY DEPTNO;

--- 8-19(2)
SELECT  D.DEPTNO,
        D.DNAME, E.ENAME, E.JOB, E.SAL
    FROM EMP E RIGHT OUTER JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    ORDER BY DEPTNO;

--- 8-20(1)
SELECT  D.DEPTNO, D.DNAME, 
        E1.EMPNO, E1.MGR, E1.SAL, E1.DEPTNO,
        S.LOSAL, S.HISAL, S.GRADE,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM DEPT D, EMP E1, SALGRADE S, EMP E2
    WHERE D.DEPTNO = E1.DEPTNO(+)
        AND E1.SAL BETWEEN LOSAL(+) AND HISAL(+)
        AND E1.MGR = E2.EMPNO(+)
    ORDER BY D.DEPTNO, E1.EMPNO;
    
--- 8-20(2)
SELECT  D.DEPTNO, D.DNAME, 
        E1.EMPNO, E1.MGR, E1.SAL, E1.DEPTNO,
        S.LOSAL, S.HISAL, S.GRADE,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
    FROM DEPT D LEFT OUTER JOIN EMP E1 ON (D.DEPTNO = E1.DEPTNO)
           LEFT OUTER JOIN SALGRADE S ON (E1.SAL BETWEEN LOSAL AND HISAL)
           LEFT OUTER JOIN EMP E2 ON (E1.MGR = E2.EMPNO)
    ORDER BY D.DEPTNO, E1.EMPNO;
    